name: publish

on:
  push:
    branches: [ main,develop ]

env:
  
  AZURE_WEBAPP_PACKAGE_PATH: '.' # Set this to the path to your web app project, defaults to the repository root:
  DOTNET_VERSION: '6.0' # The .NET SDK version to use

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: |
        cd UserManageExample        
        dotnet restore
    - name: Test
      run: |
        cd UMTest
        dotnet test --no-restore --verbosity normal  
    - name: Build
      run: |
        cd UserManageExample
        dotnet build --configuration Release --no-restore        
   
   
